# -*- coding: utf-8 -*-
"""zadania 06.11.23 4-6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11BXOG71OUPPPSMJeC5weJCAA153y3OJn
"""

# zad 4


def sprawdz_sume(a, b, c):
    suma_dwóch_pierwszych = a + b
    return suma_dwóch_pierwszych >= c


# Przykład użycia funkcji:
argument1 = 4
argument2 = 5
argument3 = 16

wynik = sprawdz_sume(argument1, argument2, argument3)
print(wynik)


# zad 5

def sprawdz_obecnosc_wartosci(lista, wartosc):
    return wartosc in lista


# Przykład użycia funkcji:
moja_lista = [1, 2, 3, 4, 5]
moja_wartosc = 7

wynik = sprawdz_obecnosc_wartosci(moja_lista, moja_wartosc)
print(wynik)


# zad 6
def polacz_i_przetworz_listy(lista1, lista2):
    # Połącz listy
    polaczona_lista = lista1 + lista2

    # Usuń duplikaty
    unikalna_lista = list(set(polaczona_lista))

    # Podnieś każdy element do potęgi 3 stopnia
    przetworzona_lista = [x**3 for x in unikalna_lista]

    return przetworzona_lista

# Przykład użycia funkcji:


lista_1 = [1, 5, 3]
lista_2 = [3, 3, 7]

wynik = polacz_i_przetworz_listy(lista_1, lista_2)
print(wynik)
