# -*- coding: utf-8 -*-
"""30.10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhVMK5D_188mEFmdm3PTeR4d7pNjfjLi

Zadanie 1
"""


def wyswietl_imiona(imiona):
    if len(imiona) != 5:
        for imie in imiona:
            print(imie)
    else:

        for imie in imiona:
            print(imie)


lista_imion = ["Jakub", "Ola", "Darek", "Łukasz", "Ewa"]

wyswietl_imiona(lista_imion)

"""Zadanie 2"""


# Wersja 1
def pomnoz_elementy(lista1):
    wynik1 = []
    for liczba in lista1:
        wynik1.append(liczba * 2)
    return wynik1


lista: List[int] = [1, 2, 3, 4, 5]
wynik = pomnoz_elementy(lista)

print(wynik)


# Wersja 2
def pomnoz_elementy(lista1):
    return [liczba * 2 for liczba in lista1]


lista = [1, 2, 3, 4, 5]
wynik = pomnoz_elementy(lista)
print(wynik)

"""Zadanie 3"""


def wyswietl_parzyste_elementy(lista):
    for liczba in lista:
        if liczba % 2 == 0:
            print(liczba)


lista = list(range(1, 11))
wyswietl_parzyste_elementy(lista)

"""Zadanie 4"""


def wyswietl_co_drugi_element(lista1):
    for i in range(0, len(lista1), 2):
        print(lista1[i])


lista = list(range(1, 11))
wyswietl_co_drugi_element(lista)
